name: CI - Update QA Branch

on:
  push:
    branches:
      - development_branch
      
permissions:
  contents: write

jobs:
  update-qa-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Development Branch
        uses: actions/checkout@v3
        with:
          ref: development_branch

      - name: Merge into QA Branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git checkout -b qa_branch origin/qa_branch
          git merge --allow-unrelated-histories --no-ff --no-edit development_branch
          git push origin qa_branch
