name: CI - Push to qa_branch

on:
  push:
    branches:
      - development_branch
      
permissions:
  contents: write

jobs:
  push-to-qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: development_branch

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Push to qa_branch
        run: |
          git checkout -b qa_branch origin/qa_branch
          git merge --allow-unrelated-histories development_branch
          git push origin qa_branch
